#courses
mk8_abbrv = [
    'mks',
    'wp',
    'ssc',
    'tr',
    'mc',
    'th',
    'tm',
    'sgf',
    'sa',
    'ds',
    'ed',
    'mw',
    'cc',
    'bdd',
    'bc',
    'rr',
    'rmmm',
    'rmc',
    'rccb',
    'rtt',
    'rddd',
    'rdp3',
    'rrry',
    'rdkj',
    'rws',
    'rsl',
    'rmp',
    'ryv',
    'rttc',
    'rpps',
    'rgv',
    'rrrd',
    'dyc',
    'dea',
    'ddd',
    'dmc',
    'dwgm',
    'drr',
    'diio',
    'dhc',
    'dbp',
    'dcl',
    'dww',
    'dac',
    'dnbc',
    'drir',
    'dsbs',
    'dbb',
    'bpp',
    'btc',
    'bcmo',
    'bcma',
    'btb',
    'bsr',
    'bsg',
    'bnh'
    ]

mk8_full = [
    'Mario Kart Stadium',
    'Water Park',
    'Sweet Sweet Canyon',
    'Thwomp Ruins',
    'Mario Circuit',
    'Toad Harbor',
    'Twisted Mansion',
    'Shy Guy Falls',
    'Sunshine Airport',
    'Dolphin Shoals',
    'Electrodrome',
    'Mount Wario',
    'Cloudtop Cruise',
    'Bone-Dry Dunes',
    'Bowser\'s Castle',
    'Rainbow Road',
    'Wii Moo Moo Meadows',
    'GBA Mario Circuit',
    'DS Cheep Cheep Beach',
    'N64 Toad\'s Turnpike',
    'GCN Dry Dry Desert',
    'SNES Donut Plains 3',
    'N64 Royal Raceway',
    '3DS DK Jungle',
    'DS Wario Stadium',
    'GCN Sherbet Land',
    '3DS Music Park',
    'N64 Yoshi Valley',
    'DS Tick-Tock Clock',
    '3DS Piranha Plant Slide',
    'Wii Grumble Volcano',
    'N64 Rainbow Road',
    'GCN Yoshi Circuit',
    'Excitebike Arena',
    'Dragon Driftway',
    'Mute City',
    'Wii Wario\'s Gold Mine',
    'SNES Rainbow Road',
    'Ice Ice Outpost',
    'Hyrule Circuit',
    'GCN Baby Park',
    'GBA Cheese Land',
    'Wild Woods',
    'Animal Crossing',
    '3DS Neo Bowser City',
    'GBA Ribbon Road',
    'Super Bell Subway',
    'Big Blue',
    'Tour Paris Promenade',
    '3DS Toad Circuit',
    'N64 Choco Mountain',
    'Wii Coconut Mall',
    'Tour Tokyo Blur',
    'DS Shroom Ridge',
    'GBA Sky Garden',
    'Tour Ninja Hideaway'
    ]
